function itemCls(name) {
    var txt = {
        "Css" : "Bitters cronut butcher, +1 dreamcatcher readymade fingerstache cray synth bespoke godard. Street art franzen polaroid gentrify. Lo-fi typewriter banh mi, lomo shabby chic asymmetrical street art craft beer narwhal heirloom. Gluten-free fixie readymade sartorial dreamcatcher godard DIY cold-pressed meggings distillery. Gochujang hoodie viral, yuccie taxidermy squid pork belly. Yr locavore pinterest pork belly thundercats heirloom, forage disrupt. Gochujang dreamcatcher kinfolk, kale chips pabst vegan green juice direct trade small batch vice lumbersexual farm-to-table art party chartreuse godard.",
        "Pug" : "Hoodie four loko letterpress freegan skateboard sartorial, polaroid forage ramps 8-bit direct trade. Chia chicharrones humblebrag 8-bit. Intelligentsia semiotics 8-bit banjo poutine chillwave. +1 small batch vegan, truffaut crucifix taxidermy twee banjo meggings blog scenester ugh. Keffiyeh readymade art party cold-pressed. Heirloom pork belly photo booth scenester cold-pressed neutra. Vice actually shoreditch viral poutine, vinyl fanny pack retro etsy kickstarter.",
        "Gulp" : "Single-origin coffee tilde craft beer organic wolf. Plaid kickstarter vegan roof party vice, try-hard taxidermy truffaut small batch. PBR&B butcher helvetica, green juice craft beer kickstarter skateboard. +1 selvage VHS gastropub slow-carb, twee vegan helvetica farm-to-table marfa seitan letterpress narwhal squid cliche. Meggings fap leggings slow-carb kickstarter, health goth gastropub hashtag blue bottle photo booth literally PBR&B iPhone ugh. Organic scenester truffaut pug, pitchfork man bun artisan brooklyn photo booth. Biodiesel farm-to-table 8-bit direct trade humblebrag, man braid blue bottle.",
        "HTML5" : "Austin artisan cornhole, microdosing messenger bag neutra tilde ramps chambray knausgaard. Messenger bag helvetica dreamcatcher migas, pork belly cold-pressed actually schlitz viral green juice vegan. XOXO mustache butcher, artisan shoreditch beard seitan lo-fi locavore banh mi skateboard organic. Sriracha ennui synth, viral chartreuse gentrify umami. Beard pour-over single-origin coffee, direct trade post-ironic keytar roof party twee shoreditch. Godard heirloom wolf, pabst pickled offal shoreditch. Kogi gentrify truffaut, viral irony kickstarter tumblr pop-up kitsch jean shorts next level cold-pressed.",
        "jQuery" : "Keffiyeh tumblr street art cold-pressed jean shorts. Street art pug 3 wolf moon cronut. Bicycle rights XOXO fanny pack cliche, cardigan meh distillery art party viral fixie roof party shabby chic kinfolk ethical yr. Poutine typewriter flannel pickled, chartreuse listicle brunch portland synth godard. Selfies echo park lo-fi ramps bespoke ugh, crucifix heirloom waistcoat squid literally. Craft beer green juice yr vinyl, sriracha pork belly pop-up seitan etsy put a bird on it truffaut. Paleo chartreuse drinking vinegar, try-hard heirloom letterpress 90's hella godard fashion axe man bun VHS pour-over farm-to-table."
    }

}
$("li").click(function () {

    console.log(this.innerHTML, itemCls.Css)
})